<?xml version="1.0" encoding="UTF-8" standalone="yes" ?><!DOCTYPE PROJECT [
 <!ELEMENT PROJECT (TARGETLIST,TARGETORDER,GROUPLIST,DESIGNLIST?)>
 <!ELEMENT TARGETLIST (TARGET)+>
 <!ELEMENT TARGET (NAME,SETTINGLIST,FILELIST?,LINKORDER?,SEGMENTLIST?,OVERLAYGROUPLIST?,SUBTARGETLIST?,SUBPROJECTLIST?,FRAMEWORKLIST?)>
 <!ELEMENT NAME (#PCDATA)>
 <!ELEMENT USERSOURCETREETYPE (#PCDATA)>
 <!ELEMENT PATH (#PCDATA)>
 <!ELEMENT FILELIST (FILE)*>
 <!ELEMENT FILE (PATHTYPE,PATHROOT?,ACCESSPATH?,PATH,PATHFORMAT?,ROOTFILEREF?,FILEKIND?,FILEFLAGS?)>
 <!ELEMENT PATHTYPE (#PCDATA)>
 <!ELEMENT PATHROOT (#PCDATA)>
 <!ELEMENT ACCESSPATH (#PCDATA)>
 <!ELEMENT PATHFORMAT (#PCDATA)>
 <!ELEMENT ROOTFILEREF (PATHTYPE,PATHROOT?,ACCESSPATH?,PATH,PATHFORMAT?)>
 <!ELEMENT FILEKIND (#PCDATA)>
 <!ELEMENT FILEFLAGS (#PCDATA)>
 <!ELEMENT FILEREF (TARGETNAME?,PATHTYPE,PATHROOT?,ACCESSPATH?,PATH,PATHFORMAT?)>
 <!ELEMENT TARGETNAME (#PCDATA)>
 <!ELEMENT SETTINGLIST (SETTING|PANELDATA)+>
 <!ELEMENT SETTING (NAME?,(VALUE|SETTING+))>
 <!ELEMENT PANELDATA (NAME,VALUE)>
 <!ELEMENT VALUE (#PCDATA)>
 <!ELEMENT LINKORDER (FILEREF)*>
 <!ELEMENT SEGMENTLIST (SEGMENT)+>
 <!ELEMENT SEGMENT (NAME,ATTRIBUTES?,FILEREF*)>
 <!ELEMENT ATTRIBUTES (#PCDATA)>
 <!ELEMENT OVERLAYGROUPLIST (OVERLAYGROUP)+>
 <!ELEMENT OVERLAYGROUP (NAME,BASEADDRESS,OVERLAY*)>
 <!ELEMENT BASEADDRESS (#PCDATA)>
 <!ELEMENT OVERLAY (NAME,FILEREF*)>
 <!ELEMENT SUBTARGETLIST (SUBTARGET)+>
 <!ELEMENT SUBTARGET (TARGETNAME,ATTRIBUTES?,FILEREF?)>
 <!ELEMENT SUBPROJECTLIST (SUBPROJECT)+>
 <!ELEMENT SUBPROJECT (FILEREF,SUBPROJECTTARGETLIST)>
 <!ELEMENT SUBPROJECTTARGETLIST (SUBPROJECTTARGET)*>
 <!ELEMENT SUBPROJECTTARGET (TARGETNAME,ATTRIBUTES?,FILEREF?)>
 <!ELEMENT FRAMEWORKLIST (FRAMEWORK)+>
 <!ELEMENT FRAMEWORK (FILEREF,LIBRARYFILE?,VERSION?)>
 <!ELEMENT LIBRARYFILE (FILEREF)>
 <!ELEMENT VERSION (#PCDATA)>
 <!ELEMENT TARGETORDER (ORDEREDTARGET|ORDEREDDESIGN)*>
 <!ELEMENT ORDEREDTARGET (NAME)>
 <!ELEMENT ORDEREDDESIGN (NAME,ORDEREDTARGET+)>
 <!ELEMENT GROUPLIST (GROUP|FILEREF)*>
 <!ELEMENT GROUP (NAME,((GROUP|FILEREF))*)>
 <!ELEMENT DESIGNLIST (DESIGN)+>
 <!ELEMENT DESIGN (NAME,DESIGNDATA)>
 <!ELEMENT DESIGNDATA (#PCDATA)>
]><?codewarrior exportversion="1.0.1" ideversion="5.0" ?><PROJECT>
    <TARGETLIST>
        <TARGET>
            <NAME>WINSCW UDEB</NAME>
            <SETTINGLIST>

                <!-- Settings for "Source Trees" panel -->
                <SETTING><NAME>UserSourceTrees</NAME></SETTING>

                <!-- Settings for "Access Paths" panel -->
                <SETTING><NAME>AlwaysSearchUserPaths</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>InterpretDOSAndUnixPaths</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>RequireFrameworkStyleIncludes</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>UserSearchPaths</NAME>
                    <SETTING>
<SETTING><NAME>SearchPath</NAME>
<SETTING><NAME>Path</NAME><VALUE>..\INC</VALUE></SETTING>
<SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
<SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>
</SETTING><SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
</SETTING><SETTING>
<SETTING><NAME>SearchPath</NAME>
<SETTING><NAME>Path</NAME><VALUE>..\LOC</VALUE></SETTING>
<SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
<SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>
</SETTING><SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
</SETTING><SETTING>
<SETTING><NAME>SearchPath</NAME>
<SETTING><NAME>Path</NAME><VALUE/></SETTING>
<SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
<SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>
</SETTING><SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
</SETTING><SETTING>
<SETTING><NAME>SearchPath</NAME>
<SETTING><NAME>Path</NAME><VALUE>..\SRC</VALUE></SETTING>
<SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
<SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>
</SETTING><SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
</SETTING></SETTING>
		        <SETTING><NAME>SystemSearchPaths</NAME>
		            <SETTING>
<SETTING><NAME>SearchPath</NAME>
<SETTING><NAME>Path</NAME><VALUE>EPOC32\INCLUDE</VALUE></SETTING>
<SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
<SETTING><NAME>PathRoot</NAME><VALUE>series60 S60_2nd_FP3</VALUE></SETTING>
</SETTING><SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
</SETTING><SETTING>
<SETTING><NAME>SearchPath</NAME>
<SETTING><NAME>Path</NAME><VALUE>EPOC32\RELEASE\WINSCW\UDEB</VALUE></SETTING>
<SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
<SETTING><NAME>PathRoot</NAME><VALUE>series60 S60_2nd_FP3</VALUE></SETTING>
</SETTING><SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
</SETTING><SETTING>
<SETTING><NAME>SearchPath</NAME>
<SETTING><NAME>Path</NAME><VALUE>Symbian_Support\Win32-x86 Support\Libraries\Win32 SDK</VALUE></SETTING>
<SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
<SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING>
</SETTING><SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
<SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
</SETTING></SETTING>

                <!-- Settings for "Debugger Runtime" panel -->
                <SETTING><NAME>MWRuntimeSettings_WorkingDirectory</NAME><VALUE/></SETTING>
                <SETTING><NAME>MWRuntimeSettings_CommandLine</NAME><VALUE/></SETTING>
                <SETTING><NAME>MWRuntimeSettings_HostApplication</NAME>
                    <SETTING><NAME>Path</NAME><VALUE>EPOC32\RELEASE\WINSCW\UDEB\epoc.exe</VALUE></SETTING>
<SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
<SETTING><NAME>PathRoot</NAME><VALUE>series60 S60_2nd_FP3</VALUE></SETTING>
</SETTING>
                <SETTING><NAME>MWRuntimeSettings_EnvVars</NAME><VALUE/></SETTING>

                <!-- Settings for "Target Settings" panel -->
                <SETTING><NAME>Linker</NAME><VALUE>Symbian Linker v2</VALUE></SETTING>
                <SETTING><NAME>PreLinker</NAME><VALUE/></SETTING>
                <SETTING><NAME>PostLinker</NAME><VALUE>Symbian Installer v2</VALUE></SETTING>
                <SETTING><NAME>Targetname</NAME><VALUE>WINSCW UDEB</VALUE></SETTING>
                <SETTING><NAME>OutputDirectory</NAME>
                    <SETTING><NAME>Path</NAME><VALUE>EPOC32\RELEASE\WINSCW\UDEB\Z\SYSTEM\APPS\KEYMAN</VALUE></SETTING>
<SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
<SETTING><NAME>PathRoot</NAME><VALUE>series60 S60_2nd_FP3</VALUE></SETTING>
</SETTING>
                <SETTING><NAME>SaveEntriesUsingRelativePaths</NAME><VALUE>false</VALUE></SETTING>

                <!-- Settings for "File Mappings" panel -->
		        <SETTING><NAME>FileMappings</NAME>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.c</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE>Symbian Compiler v2</VALUE></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.cc</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE>Symbian Compiler v2</VALUE></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.cfg</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.cia</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE>Symbian Compiler v2</VALUE></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.cpp</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE>Symbian Compiler v2</VALUE></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.cwlink</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>XML</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.cxx</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE>Symbian Compiler v2</VALUE></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.def</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE/></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.h</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE>Symbian Compiler v2</VALUE></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.hrh</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.i</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE>Symbian Compiler v2</VALUE></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.iby</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.ii</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE>Symbian Compiler v2</VALUE></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.inf</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.ini</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.loc</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.mmp</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.mmpi</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.pkg</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.policy</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.ra</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.resources</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE>Symbian Resource v2</VALUE></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>XML</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>true</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.rh</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.rls</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.rss</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.s</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE>Symbian Compiler v2</VALUE></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.script</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.txt</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE/></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.a</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE>Symbian Object Importer v2</VALUE></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE/></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.lib</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE>Symbian Object Importer v2</VALUE></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE/></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
		            <SETTING>
		                <SETTING><NAME>FileExtension</NAME><VALUE>.o</VALUE></SETTING>
		                <SETTING><NAME>Compiler</NAME><VALUE>Symbian Object Importer v2</VALUE></SETTING>
		                <SETTING><NAME>EditLanguage</NAME><VALUE/></SETTING>
		                <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
		                <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
		            </SETTING>
                </SETTING>

                <!-- Settings for "Build Extras" panel -->
                <SETTING><NAME>CacheModDates</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>DumpBrowserInfo</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>CacheSubprojects</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>UseThirdPartyDebugger</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>BrowserGenerator</NAME><VALUE>2</VALUE></SETTING>
                <SETTING><NAME>DebuggerAppPath</NAME>
                    <SETTING><NAME>Path</NAME><VALUE/></SETTING>
                    <SETTING><NAME>PathFormat</NAME><VALUE>Generic</VALUE></SETTING>
                    <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>
                </SETTING>